version: 2
updates:
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "weekly"
        open-pull-requests-limit: 20  # override the default 10
    -   package-ecosystem: "maven"
        directory: "/"
        schedule:
            interval: "weekly"
        open-pull-requests-limit: 20  # override the default 10
    -   package-ecosystem: "docker"
        directory: "/"
        schedule:
            interval: "weekly"
        open-pull-requests-limit: 20  # override the default 10
